modLoader="javafml"
loaderVersion="[43,)"
license="The Apache License, Version 2.0"
issueTrackerURL=""

[[mods]]
modId="sandbox"
version="${file.jarVersion}"
displayName="SandBox"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sand_box"
updateJSONURL="https://assets.melanx.de/updates/sand_box.json"
authors="noeppi_noeppi"
description="""
A worldgen library.
"""

[[dependencies.sandbox]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sandbox]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sandbox]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.2-4.2.5,)"
    ordering="NONE"
    side="BOTH"

